### ISSUE TITLE
Wayland lifetime issues

### ISSUE THREAD

**Issue by i509VCB** [rust-windowing/softbuffer#11]
A few things I noticed:
The WlShm and WlShmPool protocol objects are leaked when dropping a GraphicsContext

The client could modify pixels while the compositor is using the buffer. This is not allowed per wl_surface protocol.
> Committing a pending wl_buffer allows the compositor to read the
> pixels in the wl_buffer. The compositor may access the pixels at
> any time after the wl_surface.commit request. When the compositor
> will not access the pixels anymore, it will send the
> wl_buffer.release event. Only after receiving wl_buffer.release,
> the client may reuse the wl_buffer. A wl_buffer that has been
> attached and then replaced by another attach instead of committed
> will not receive a release event, and is not used by the
> compositor.

In order to handle that safely, setting the buffer while the compositor is using the previous buffer either needs to tell the user to wait, needs to block or use double buffering. 

Also because of this requirement, dropping a GraphicsContext implies we must block until the compositor to releases the buffer.

**Comment by ids1024** [comment]
The behavior should be correct now.
