### ISSUE TITLE
Windows CI flaky test

### ISSUE THREAD

**Issue by daxpedda** [rust-windowing/softbuffer#119]
Not sure if this is still an actual bug or just flaky on CI.

Attempted fix: https://github.com/rust-windowing/softbuffer/pull/104/commits/65b5d489dbfb377d5baacfe38f2f54b0c1ec8c50
Related: https://github.com/rust-windowing/softbuffer/pull/104#issuecomment-1573065754

**Comment by notgull** [comment]
Ameliorated this via #138
