### ISSUE TITLE
buffer width and height are only u16

### ISSUE THREAD

**Issue by LoganDark** [rust-windowing/softbuffer#13]
This limits the window to 65,536 * 65,536. :/

Is there any reason for this limitation, does a backend mandate it or something?

**Comment by i509VCB** [comment]
I know X11 limits window dimensions to a u16. Wayland is everything greater than zero within an `i32` (so effectively a u31).

**Comment by LoganDark** [comment]
> I know X11 limits window dimensions to a u16.

This is a platform-specific-panic sort of situation - if you ever do encounter a window bigger than that, anyway.

**Comment by kchibisov** [comment]
In what setup would you need to create a buffer that large? I'm not even sure you can achieve a resolution like that, and both windows and X11 limit to u16?

65536 * 65536 window will consume 128 GB of memory, sure, you'll have a window that large.

Not even speaking about bandwidth you'd need for it.

**Comment by LoganDark** [comment]
> In what setup would you need to create a buffer that large? I'm not even sure you can achieve a resolution like that, and both windows and X11 limit to u16?
> 
> 65536 * 65536 window will consume 128 GB of memory, sure, you'll have a window that large.
> 
> Not even speaking about bandwidth you'd need for it.

You only have to exceed it in 1 dimension for there to be an issue, and 8K monitors famously have like 7680 pixels across, it's feasible to exceed 65536 *today* with like 10 of these monitors in a row.

This is somewhat of a contrived scenario but 65536 is only like 1 or 2 orders of magnitude off from a normal desktop setup which makes me uncomfortable. I would much rather softbuffer use u32 internally even if 80% of its backends will panic. Because then maybe those backends can be updated without breaking changes if the API is future-proof.

**Comment by kchibisov** [comment]
>8–9 of these monitors in a row.

128GB of memory for a single frame, sure you have that many video memory for a single window on a GPU. maybe in 50 years. Like what you describe isn't possible and no system will ever handle that in 2 decades or unless we have RAM in TB instead of GB. So with 32TB of ram I'll be comfortable using such thing.

>Because then maybe those backends can be updated without breaking changes if the API is future-proof.

Breaking change to WinAPI/X11 protocol btw.

**Comment by ids1024** [comment]
> it's feasible to exceed 65536 today with like 8–9 of these monitors in a row

"Feasible" may be an exaggeration. I don't think you'll find any GPU that can drive 9 8k displays. Can they even handle 2? If so that would require displays connected to 5 different graphics cards. At best "technically possible" rather than "feasible".

I don't really expect this to be an issue in the foreseeable future. But I think it makes sense to use 32-bit values when that's what winit uses (as well as glutin), and is technically supported on some backends.

**Comment by i509VCB** [comment]
Maybe the compromise to take here would be to introduce a sort of `Limits` type you can query from a `Context` that way backends which support higher horizontal resolutions can advertise that.

**Comment by john01dav** [comment]
> Maybe the compromise to take here would be to introduce a sort of `Limits` type you can query from a `Context` that way backends which support higher horizontal resolutions can advertise that.

I'm seriously skeptical of if we need this extra complexity. It provides little advantage over just having a function to give a maximum value.

**Comment by ids1024** [comment]
> Maybe the compromise to take here would be to introduce a sort of Limits type you can query from a Context that way backends which support higher horizontal resolutions can advertise that.

In a typical use case one wants to use a buffer size that's the same as the size of the window, obtained from something like winit, so softbuffer itself doesn't need to expose any information about the range of acceptable values. Not sure if there are any real cases where this would be needed.

**Comment by i509VCB** [comment]
> > Maybe the compromise to take here would be to introduce a sort of `Limits` type you can query from a `Context` that way backends which support higher horizontal resolutions can advertise that.
> 
> I'm seriously skeptical of if we need this extra complexity. It provides little advantage over just having a function to give a maximum value.

Considering there may be a future kms/drm backend that could use dumb buffers, the display hardware may limit the maximum size of the buffer or even what sizes are valid. Although that probably depends more on knowing the allowed display modes which winit would advertise.

**Comment by kchibisov** [comment]
>idk my calculations say nine 8K monitors would be 298,598,400 pixels, or in other words 900MB for 24 bpp, because I am not taking about 64k x 64k I'm talking about 64k x anything

Ok, 8GB per window buffer in that setup, if we use 64kx4K. Maybe you'll be able to open 4 windows and call it a day(be aware that most systems don't support u32).

I'm pushing U16, only because Windows/X11 are limited to U16, and they won't change that, no one will break WinAPI. Probably Wayland will be able to handle that, but you'll run out of memory.

Sure, we could have a U32, it's more pointless error handling.

**Comment by ids1024** [comment]
> Considering there may be a future kms/drm backend that could use dumb buffers, the display hardware may limit the maximum size of the buffer or even what sizes are valid. Although that probably depends more on knowing the allowed display modes which winit would advertise.
>
> The kms/drm use case would probably want that size on the surface itself then and not the context.

Interesting point. Currently it's implied that you could use any size from `1` to `u16::MAX`. But behavior may be weird if you use any size that isn't already established as the window size. A minimum size or only allowing specific sizes could be worked around by allocating a larger dumb buffer, and providing a reference to the start of it. But an upper limit that depends on graphics hardware and isn't just absurdly large is more complicated.

But anyway, the examples primary just use the width and height that is returned by winit's `Window::inner_size`, and this seems to be the generally expected way to use `softbuffer`. That currently uses `u32`, so anything more restrictive would require the caller to use failable conversion. If that could never be `0`, it would make sense for winit to instead use `NonZeroU32` (which as also what glutin currently uses). In some semver breaking release. Would it make sense for winit to use `NonZeroU16`? In which case would winit panic or clamp the value if Wayland sent a `configure` with an out of range value?

For usability from the caller's perspective, matching the type used in winit is probably more important that what maximum is technically supported.

**Comment by john01dav** [comment]
If we don't need to support sizes buffer other than the window size, we could work with the type of API being created in #65 to just have that be the size of the owned buffer, where the user can't directly and/or safely change it. Then, the buffer size can be given as a u32 and the concerns about handling >65536 passed from the user are addressed.

**Comment by notgull** [comment]
Closed in #65
