### ISSUE TITLE
Bump deps and make a release

### ISSUE THREAD

**Issue by kchibisov** [rust-windowing/softbuffer#162]
Basically:

#161
#159
#158 
#147 (maybe)
#132

**Comment by ids1024** [comment]
These things are done now, other than https://github.com/rust-windowing/softbuffer/pull/132.

We could do a patch release now, though none of the updates are especially important.

The `raw-window-handle` update will be breaking, and I guess should be done alongside the release of winit. Unless we can support both versions in some clean way.

**Comment by kchibisov** [comment]
The main motivation is to include updated softbuffer for the winit release, so we don't have duplicated deps.

**Comment by pixelgaming579** [comment]
Unsure if this should go in a new issue or not, but winit has had a softbuffer-breaking update - [Winit Version 0.29.2](https://github.com/rust-windowing/winit/releases/tag/v0.29.2).

**Comment by kchibisov** [comment]
I mean, it doesn't matter though. You can still use softbuffer with new winit, just use a `rwh_05` feature. And winit doesn't depend on softbuffer.
