### ISSUE TITLE
Replace `winapi` with `windows`

### ISSUE THREAD

**Issue by daxpedda** [rust-windowing/softbuffer#26]
[`winapi`](https://crates.io/crates/winapi) is not maintained anymore. The newer [`windows`](https://crates.io/crates/windows) crate is the official Rust bindings library to the Windows API.

It also helps with compile times, as all other big libraries have also switched to `windows`, like `winit` for example.

**Comment by jpxor** [comment]
I'm getting a bunch of errors like this:
```
error[E0432]: unresolved import `winapi::shared::windef`
 --> ...\softbuffer-0.1.1\src\win32.rs:4:21
  |
4 | use winapi::shared::windef::{HDC, HWND};
  |                     ^^^^^^ could not find `windef` in `shared`
```
when trying to run the [example](https://github.com/john01dav/softbuffer#example) code on windows 10.

Is this a result of it not being maintained, or am I missing a dependency/feature?
Thanks,

**Comment by notgull** [comment]
This should now be fixed by https://github.com/rust-windowing/softbuffer/commit/85b4f189bd152b580f52bf138a31db65bfff5a5a.
