### ISSUE TITLE
Managed buffer support

### ISSUE THREAD

**Issue by LoganDark** [rust-windowing/softbuffer#27]
As mentioned when #16 was closed, it would be nice if `softbuffer` could provide a managed buffer to avoid the cost of copying. I'm imagining a double-buffered setup where you can call a function to swap the buffers.

Currently softbuffer can take up to 3-4ms to upload the buffer to the window, which is really slow. (edit: even slower with larger windows; see #18)

API design for this could be somewhat difficult but I doubt it'll be too hard. I can propose designs if you like

**Comment by ids1024** [comment]
Closing in favor of https://github.com/rust-windowing/softbuffer/issues/40, since that has more discussion at this point.
