### ISSUE TITLE
Update the crates.io version

### ISSUE THREAD

**Issue by marceline-cramer** [rust-windowing/softbuffer#28]
Hi, I'm using softbuffer in my toy terminal emulator project on Wayland, and I had to pull softbuffer as a git dependency in order for it to do proper Wayland damage tracking on redraws. Could you please publish the latest master onto crates.io?

**Comment by john01dav** [comment]
I have been meaning to for a little bit already, but there are a few things
that I wanted to finish first (namely making the Wayland implementation
better). I'll push a new version soon, probably without the completely
improved Wayland implementation.

**Comment by marceline-cramer** [comment]
> I have been meaning to for a little bit already, but there are a few things that I wanted to finish first (namely making the Wayland implementation better). I'll push a new version soon, probably without the completely improved Wayland implementation.

I had been meaning to fork softbuffer and make my own improvements on Wayland. Do you need help with anything?

**Comment by john01dav** [comment]
Any PRs that you'd like to offer with any Wayland improvements would be
greatly appreciated. It's pretty obvious what the issues are just from
running the examples, but I can collect a list of specific issues if you
prefer. Do you have any experience with Wayland? That API is sufficiently
complicated that it feels like I need to read a book on it to make
everything work fully properly. I'd like to do that amount of reading on it
at some point, but I don't have the time right now.

**Comment by marceline-cramer** [comment]
I don't have much hands-on experience with Wayland, no, but I figure that something like double-buffering (to get rid of the screen-tearing during normal operation and shearing on resize, would fix #11) would be pretty straight-forward to implement. I was planning on referencing tried-and-true Wayland shm implementations like minifb and [foot](https://codeberg.org/dnkl/foot), but if that doesn't work, I can take the time myself to learn the nitty-gritty specifics of Wayland. I need shared memory-based CPU graphics in lots of the projects I do, so I'm happy to put a lot of time into softbuffer's Wayland backend if it means that my projects can run on non-Wayland for other people too.

There are two major issues that I've personally noticed while using softbuffer that I plan to fix:
- My compositor (Sway) greatly slows down with more than a few full-screen softbuffer windows updating. I want to add damage rects (#9) to the API to reduce the strain on the compositor.
- Transparency is unsupported (#17). I can add this for Wayland and X11 (again, by referencing working impls) but not for other platforms. This would also require an API change.

**Comment by jackpot51** [comment]
0.2.0 is now released, see the changelog for changes.
