### ISSUE TITLE
Damage in presentation

### ISSUE THREAD

**Issue by i509VCB** [rust-windowing/softbuffer#39]
In order to efficiently draw on the CPU, it may be desireable to reduce how many pixels are actually drawn.

Often this involves telling the display server what pixels were changed so that the display server can reuse it's existing framebuffer or perform a partial upload of the texture data to the gpu to save pci bandwidth.

**Comment by ids1024** [comment]
Now that https://github.com/rust-windowing/softbuffer/pull/65 is merged, we could have a `present_with_damage()` method.

This is natural enough on Wayland. Do other backends have a way to support this?
