### ISSUE TITLE
Supporting both Xlib and Xcb raw window handles

### ISSUE THREAD

**Issue by i509VCB** [rust-windowing/softbuffer#45]
X11 is one of the rare platforms with two libraries that interface with the protocol. Ideally swbuf should support working with both Xcb and Xlib handles.

**Comment by i509VCB** [comment]
One thing that might also be worth considering is having the Xlib backend simply use the underlying xcb connection. This would require FFI of course (like the other backends using raw-window-handle).

**Comment by ids1024** [comment]
Avoiding duplication like that would definitely be better. Presumably every system running an X server from the past decade and a half would have the version of xlib that's based on xcb.
