### ISSUE TITLE
Handle scale factor change on macOS

### ISSUE THREAD

**Issue by kpreid** [rust-windowing/softbuffer#67]
The macOS code in softbuffer 0.2.0 consults `backingScaleFactor()` only when the graphics context is created. This means that, assuming the application always renders an image of the window's physical size, the image will display at the wrong scale (half or double) if the window has been dragged between monitors with different scale factors. Instead, the scale factor should probably be consulted at every `set_buffer()` call.

**Comment by tronical** [comment]
Excellent idea to do that in `set_buffer`. I've made a PR that tries to do that.
