### ISSUE TITLE
README.md Example not working (outdated?)

### ISSUE THREAD

**Issue by BerryArray** [rust-windowing/softbuffer#78]
The example on the README.md file ([Here](https://github.com/rust-windowing/softbuffer#example)) seems to contain structs(?) like `softbuffer::Context` and `softbuffer::Surface` which aren't in the documentation. (nor seem to exist at all?)

There's an extremely similar example used in the docs.rs softbuffer home-page ([Here](https://docs.rs/softbuffer/latest/softbuffer/index.html?search=Surface#example)) which does compile.

What's strange is that I can't seem to find any mention of `softbuffer::Context` and `softbuffer::Surface` in any of the older versions' documentation.

**Comment by ids1024** [comment]
The API was updated in https://github.com/rust-windowing/softbuffer/pull/64. The example in the README should work on the git `master` of softbuffer, but not the latest release.

**Comment by notgull** [comment]
As of now, `README.md` contains the correctly released code.
