### ISSUE TITLE
Wayland dies with broken pipe error

### ISSUE THREAD

**Issue by i509VCB** [rust-windowing/softbuffer#8]
```
[2022-05-31T18:54:38Z ERROR smithay_client_toolkit::event_loop] Error trying to flush the wayland display: Broken pipe (os error 32)
```

This error seems to imply fd leaks?

Reproduction:
1. Paste the example into a project.
2. Resize the window for about 30s

**Comment by john01dav** [comment]
I just tried to reproduce this issue on Gnome and KDE and I was unable to do so on the latest commit (d30d3255c2d64994d538ca3291c51e65ef7d9b83). Can you perhaps provide more detailed reproduction steps?

**Comment by john01dav** [comment]
I'm getting some similar issues now when I test more thoroughly on Gnome. Hopefully I'll have a fix soon

**Comment by ids1024** [comment]
This should be fixed in the current version of the Wayland backend.
