### ISSUE TITLE
A safe API wrapper interface

### ISSUE THREAD

**Issue by rbermani** [rust-windowing/softbuffer#80]
Has there been any consideration as to wrapping the unsafe bits of the user facing API into a safe abstraction?

**Comment by rbermani** [comment]
Thanks. I'll keep an eye on @notgull's project. I have been using the rust pixels crate in lieu of softbuffer for an application that doesn't actually require GPU acceleration. It appears to be hiding the RawWindowHandle inside the implementation.

**Comment by Jules-Bertholet** [comment]
`raw-window-handle` 0.5.2 now has a safe API based on notgull's work, maybe this issue could be revisited?

**Comment by notgull** [comment]
> `raw-window-handle` 0.5.2 now has a safe API based on notgull's work, maybe this issue could be revisited?

I've opened a PR (https://github.com/rust-windowing/softbuffer/pull/132) in anticipation of the new `raw-window-handle` breaking changes in the upcoming v0.6 (rust-windowing/raw-window-handle#125). 

I'd like to file equivalent draft PRs for `glutin` and `wgpu` before I release rwh v0.6. There's also [this issue](https://github.com/rust-windowing/raw-window-handle/pull/129) which needs to be resolved as well.
